# Generated by Django 5.0 on 2025-07-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.IntegerField()),
                ("content", models.TextField()),
                ("max_score", models.IntegerField()),
            ],
            options={
                "db_table": "questions",
                "ordering": ["question_number"],
            },
        ),
        migrations.CreateModel(
            name="QuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_number", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("max_score", models.IntegerField()),
            ],
            options={
                "db_table": "question_groups",
                "ordering": ["group_number"],
            },
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("japanese", "国語"),
                            ("math", "数学"),
                            ("english", "英語"),
                            ("science", "理科"),
                            ("social", "社会"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_score", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "test_definitions",
            },
        ),
        migrations.CreateModel(
            name="AnswerKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct_answer", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_key",
                        to="tests.question",
                    ),
                ),
            ],
            options={
                "db_table": "answer_keys",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tests.questiongroup",
            ),
        ),
        migrations.AddField(
            model_name="questiongroup",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_groups",
                to="tests.testdefinition",
            ),
        ),
        migrations.CreateModel(
            name="TestSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("spring", "春期"),
                            ("summer", "夏期"),
                            ("autumn", "秋期"),
                            ("winter", "冬期"),
                        ],
                        max_length=10,
                    ),
                ),
                ("planned_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "test_schedules",
                "indexes": [
                    models.Index(
                        fields=["year", "period"], name="test_schedu_year_046225_idx"
                    ),
                    models.Index(
                        fields=["deadline_at"], name="test_schedu_deadlin_414489_idx"
                    ),
                ],
                "unique_together": {("year", "period")},
            },
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="tests.testschedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("group", "question_number")},
        ),
        migrations.AlterUniqueTogether(
            name="questiongroup",
            unique_together={("test", "group_number")},
        ),
        migrations.AddIndex(
            model_name="testdefinition",
            index=models.Index(
                fields=["schedule", "subject"], name="test_defini_schedul_ad7b2d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testdefinition",
            unique_together={("schedule", "subject")},
        ),
    ]
