# Generated by Django 4.2.7 on 2025-07-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_testdefinition_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerkey",
            options={"verbose_name": "解答", "verbose_name_plural": "解答"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["question_number"],
                "verbose_name": "問題",
                "verbose_name_plural": "問題",
            },
        ),
        migrations.AlterModelOptions(
            name="questiongroup",
            options={
                "ordering": ["group_number"],
                "verbose_name": "問題グループ",
                "verbose_name_plural": "問題グループ",
            },
        ),
        migrations.AlterModelOptions(
            name="testdefinition",
            options={"verbose_name": "テスト", "verbose_name_plural": "テスト"},
        ),
        migrations.AlterModelOptions(
            name="testschedule",
            options={
                "verbose_name": "テストスケジュール",
                "verbose_name_plural": "テストスケジュール",
            },
        ),
    ]
