# Generated by Django 4.2.7 on 2025-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_alter_answerkey_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdefinition",
            name="answer_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="test_answers/", verbose_name="解答PDF"
            ),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="question_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="test_questions/",
                verbose_name="問題PDF",
            ),
        ),
    ]
