# Generated by Django 4.2.7 on 2025-07-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_testdefinition_answer_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiongroup",
            name="group_number",
            field=models.IntegerField(verbose_name="大問番号"),
        ),
    ]
