# Generated by Django 4.2.7 on 2025-07-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_alter_questiongroup_group_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questiongroup",
            options={
                "ordering": ["group_number"],
                "verbose_name": "大問",
                "verbose_name_plural": "大問",
            },
        ),
    ]
