# Generated by Django 4.2.7 on 2025-07-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_alter_questiongroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerkey",
            name="correct_answer",
            field=models.TextField(verbose_name="正解"),
        ),
        migrations.AlterField(
            model_name="answerkey",
            name="explanation",
            field=models.TextField(blank=True, verbose_name="解説"),
        ),
        migrations.AlterField(
            model_name="answerkey",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_key",
                to="tests.question",
                verbose_name="問題",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.TextField(verbose_name="問題内容"),
        ),
        migrations.AlterField(
            model_name="question",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tests.questiongroup",
                verbose_name="大問",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="max_score",
            field=models.IntegerField(verbose_name="満点"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_number",
            field=models.IntegerField(verbose_name="問題番号"),
        ),
        migrations.AlterField(
            model_name="questiongroup",
            name="max_score",
            field=models.IntegerField(verbose_name="満点"),
        ),
        migrations.AlterField(
            model_name="questiongroup",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_groups",
                to="tests.testdefinition",
                verbose_name="テスト",
            ),
        ),
        migrations.AlterField(
            model_name="questiongroup",
            name="title",
            field=models.CharField(max_length=100, verbose_name="タイトル"),
        ),
        migrations.AlterField(
            model_name="testdefinition",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ"),
        ),
        migrations.AlterField(
            model_name="testdefinition",
            name="max_score",
            field=models.IntegerField(default=100, verbose_name="満点"),
        ),
        migrations.AlterField(
            model_name="testdefinition",
            name="name",
            field=models.CharField(max_length=100, verbose_name="テスト名"),
        ),
        migrations.AlterField(
            model_name="testdefinition",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="tests.testschedule",
                verbose_name="テストスケジュール",
            ),
        ),
        migrations.AlterField(
            model_name="testdefinition",
            name="subject",
            field=models.CharField(
                choices=[("japanese", "国語"), ("math", "算数")],
                max_length=20,
                verbose_name="科目",
            ),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="actual_date",
            field=models.DateField(blank=True, null=True, verbose_name="実施日"),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="deadline_at",
            field=models.DateTimeField(verbose_name="締切日時"),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ"),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="period",
            field=models.CharField(
                choices=[
                    ("spring", "春期"),
                    ("summer", "夏期"),
                    ("autumn", "秋期"),
                    ("winter", "冬期"),
                ],
                max_length=10,
                verbose_name="時期",
            ),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="planned_date",
            field=models.DateField(verbose_name="予定日"),
        ),
        migrations.AlterField(
            model_name="testschedule",
            name="year",
            field=models.IntegerField(verbose_name="年度"),
        ),
    ]
