# Generated by Django 4.2.7 on 2025-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_alter_answerkey_correct_answer_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="testdefinition",
            name="test_defini_schedul_ad7b2d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="testdefinition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="grade_level",
            field=models.CharField(
                choices=[("elementary", "小学生"), ("middle_school", "中学生")],
                default="elementary",
                max_length=20,
                verbose_name="対象学年",
            ),
        ),
        migrations.AlterField(
            model_name="testdefinition",
            name="subject",
            field=models.CharField(
                choices=[
                    ("japanese", "国語"),
                    ("math", "算数"),
                    ("english", "英語"),
                    ("mathematics", "数学"),
                ],
                max_length=20,
                verbose_name="科目",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testdefinition",
            unique_together={("schedule", "grade_level", "subject")},
        ),
        migrations.AddIndex(
            model_name="testdefinition",
            index=models.Index(
                fields=["schedule", "grade_level", "subject"],
                name="test_defini_schedul_4e4833_idx",
            ),
        ),
    ]
