# Generated by Django 4.2.7 on 2025-07-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_remove_testdefinition_test_defini_schedul_ad7b2d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testdefinition",
            name="name",
        ),
    ]
