# Generated by Django 4.2.7 on 2025-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0010_alter_testdefinition_grade_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testschedule",
            name="period",
            field=models.CharField(
                choices=[("spring", "春期"), ("summer", "夏期"), ("winter", "冬期")],
                max_length=10,
                verbose_name="時期",
            ),
        ),
    ]
