# Generated by Django 4.2.7 on 2025-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0011_alter_testschedule_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdefinition",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("elementary_1", "小1"),
                    ("elementary_2", "小2"),
                    ("elementary_3", "小3"),
                    ("elementary_4", "小4"),
                    ("elementary_5", "小5"),
                    ("elementary_6", "小6"),
                    ("middle_1", "中1"),
                    ("middle_2", "中2"),
                    ("middle_3", "中3"),
                ],
                default="elementary_1",
                max_length=20,
                verbose_name="対象学年",
            ),
        ),
    ]
