# Generated by Django 4.2.7 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_testdefinition_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdefinition',
            name='answer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='test_answers/', verbose_name='解答ファイル'),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='question_pdf',
            field=models.FileField(blank=True, null=True, upload_to='test_questions/', verbose_name='問題ファイル'),
        ),
    ]
