# Generated by Django 4.2.7 on 2025-07-13 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "ユーザー", "verbose_name_plural": "ユーザー"},
        ),
        migrations.AlterField(
            model_name="user",
            name="classroom_id",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "6桁の数字で入力してください"
                    )
                ],
                verbose_name="教室ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("school_admin", "塾管理者"),
                    ("classroom_admin", "教室管理者"),
                ],
                max_length=20,
                verbose_name="役割",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="school_id",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "6桁の数字で入力してください"
                    )
                ],
                verbose_name="塾ID",
            ),
        ),
    ]
