# Generated by Django 5.0 on 2025-07-11 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6}$", "6桁の数字で入力してください"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="classrooms.classroom",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "indexes": [
                    models.Index(
                        fields=["classroom", "student_id"],
                        name="students_classro_92fa8d_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="students_is_acti_4aecc9_idx"
                    ),
                ],
                "unique_together": {("classroom", "student_id")},
            },
        ),
    ]
