# Generated by Django 4.2.7 on 2025-07-21 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentenrollment_student_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,10}$", "1〜10桁の数字で入力してください"
                    )
                ],
                verbose_name="生徒ID",
            ),
        ),
    ]
