# Generated by Django 4.2.7 on 2025-07-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_student_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="students_status_3ac771_idx",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status",
        ),
    ]
