# Generated by Django 4.2.7 on 2025-07-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_remove_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
    ]
