# Generated by Django

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_email'),
    ]

    operations = [
        # まずunique_togetherを削除
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        # student_idをユニークに変更
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.RegexValidator('^\\d{1,10}$', '1〜10桁の数字で入力してください')],
                verbose_name='生徒ID'
            ),
        ),
    ]
