# Generated by Django 5.0 on 2025-07-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("student_count", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "billing_records",
                "indexes": [
                    models.Index(
                        fields=["school", "year", "month"],
                        name="billing_rec_school__c3f1eb_idx",
                    ),
                    models.Index(
                        fields=["is_paid"], name="billing_rec_is_paid_91e119_idx"
                    ),
                ],
                "unique_together": {("school", "year", "month")},
            },
        ),
    ]
