services:
  # PostgreSQL データベース
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: autograder_db
      POSTGRES_USER: autograder_user
      POSTGRES_PASSWORD: autograder_password_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Django バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://autograder_user:autograder_password_2025@db:5432/autograder_db
      - DJANGO_SECRET_KEY=your-super-secret-key-change-this-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge