# Generated by Django 4.2.7 on 2025-07-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_alter_school_options_alter_school_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="active_date",
            field=models.DateField(blank=True, null=True, verbose_name="本入会日"),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_person",
            field=models.CharField(
                default="管理者", max_length=100, verbose_name="担当者名"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "体験"),
                    ("active", "本入会"),
                    ("withdrawn", "退会"),
                ],
                default="trial",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="trial_date",
            field=models.DateField(blank=True, null=True, verbose_name="体験開始日"),
        ),
        migrations.AddField(
            model_name="school",
            name="withdrawn_date",
            field=models.DateField(blank=True, null=True, verbose_name="退会日"),
        ),
    ]
