# Generated by Django 5.0 on 2025-07-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_school_active_date_school_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("culture_kids", "カルチャーキッズ導入塾"),
                    ("general", "一般塾"),
                    ("eduplus", "eduplus導入塾"),
                ],
                default="general",
                max_length=20,
                verbose_name="会員種別",
            ),
        ),
    ]
