# Generated by Django 4.2.7 on 2025-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_school_membership_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="can_input_scores",
            field=models.BooleanField(default=True, verbose_name="点数入力権限"),
        ),
        migrations.AddField(
            model_name="school",
            name="can_register_students",
            field=models.BooleanField(default=True, verbose_name="生徒登録権限"),
        ),
        migrations.AddField(
            model_name="school",
            name="can_view_reports",
            field=models.BooleanField(default=True, verbose_name="結果出力権限"),
        ),
    ]
