# Generated by Django 4.2.7 on 2025-07-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_options_alter_student_classroom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("spring", "春期"),
                            ("summer", "夏期"),
                            ("winter", "冬期"),
                        ],
                        max_length=10,
                        verbose_name="学期",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ"),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="受講開始日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "生徒受講情報",
                "verbose_name_plural": "生徒受講情報",
                "db_table": "student_enrollments",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("enrolled", "入会"), ("new", "新規"), ("withdrawn", "退会")],
                default="new",
                max_length=10,
                verbose_name="ステータス",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_status_3ac771_idx"),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
                verbose_name="生徒",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["year", "period"], name="student_enr_year_97bf36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["student", "year", "period"],
                name="student_enr_student_d453fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["is_active"], name="student_enr_is_acti_8573a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "year", "period")},
        ),
    ]
