# Generated by Django 4.2.7 on 2025-07-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_remove_student_students_status_3ac771_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="phone_number",
        ),
    ]
