# Generated by Django 5.0 on 2025-07-11 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom_id",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6}$", "6桁の数字で入力してください"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "classrooms",
                "indexes": [
                    models.Index(
                        fields=["school", "classroom_id"],
                        name="classrooms_school__f6a8f6_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="classrooms_is_acti_148ca3_idx"
                    ),
                ],
            },
        ),
    ]
