# Generated by Django 4.2.7 on 2025-07-13 03:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_alter_school_options_alter_school_address_and_more"),
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={"verbose_name": "教室", "verbose_name_plural": "教室"},
        ),
        migrations.AlterField(
            model_name="classroom",
            name="classroom_id",
            field=models.CharField(
                max_length=6,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "6桁の数字で入力してください"
                    )
                ],
                verbose_name="教室ID",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=100, verbose_name="教室名"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="schools.school",
                verbose_name="塾",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
