# Generated by Django 4.2.7 on 2025-07-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_classroom_membership_type_classroompermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("eduplus", "eduplus導入塾"),
                    ("culture_kids", "カルチャーキッズ導入塾"),
                    ("general", "一般塾"),
                ],
                default="general",
                max_length=20,
                verbose_name="会員種別",
            ),
        ),
        migrations.CreateModel(
            name="MembershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        choices=[
                            ("culture_kids", "カルチャーキッズ導入塾"),
                            ("general", "一般塾"),
                            ("eduplus", "eduplus導入塾"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="塾区分コード",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="塾区分名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "price_per_student",
                    models.IntegerField(verbose_name="1名あたり料金（円）"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "会員種別",
                "verbose_name_plural": "会員種別",
                "db_table": "membership_types",
                "indexes": [
                    models.Index(
                        fields=["type_code"], name="membership__type_co_acf556_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="membership__is_acti_03fa19_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("spring", "春期"),
                            ("summer", "夏期"),
                            ("winter", "冬期"),
                        ],
                        max_length=10,
                        verbose_name="期",
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="総生徒数"),
                ),
                (
                    "billed_students",
                    models.IntegerField(default=0, verbose_name="課金対象生徒数"),
                ),
                ("price_per_student", models.IntegerField(verbose_name="単価（円）")),
                (
                    "total_amount",
                    models.IntegerField(default=0, verbose_name="合計金額（円）"),
                ),
                (
                    "student_details",
                    models.JSONField(default=dict, verbose_name="生徒詳細"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classrooms.classroom",
                        verbose_name="教室",
                    ),
                ),
            ],
            options={
                "verbose_name": "課金レポート",
                "verbose_name_plural": "課金レポート",
                "db_table": "billing_reports",
                "indexes": [
                    models.Index(
                        fields=["year", "period"], name="billing_rep_year_ec51cf_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="billing_rep_generat_6f9187_idx"
                    ),
                ],
                "unique_together": {("classroom", "year", "period")},
            },
        ),
    ]
