# Generated by Django 5.0 on 2025-07-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0004_alter_classroom_membership_type_membershiptype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="membership_type",
        ),
    ]
