# Generated by Django 4.2.7 on 2025-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0005_remove_classroom_membership_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroompermission",
            name="can_download_tests",
        ),
        migrations.AddField(
            model_name="classroompermission",
            name="can_view_reports",
            field=models.BooleanField(default=True, verbose_name="結果出力権限"),
        ),
    ]
