# Generated by Django 4.2.7 on 2025-09-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "schools",
            "0005_school_can_input_scores_school_can_register_students_and_more",
        ),
        ("classrooms", "0006_remove_classroompermission_can_download_tests_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolBillingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("spring", "春期"),
                            ("summer", "夏期"),
                            ("winter", "冬期"),
                        ],
                        max_length=10,
                        verbose_name="期",
                    ),
                ),
                (
                    "total_classrooms",
                    models.IntegerField(default=0, verbose_name="教室数"),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="総生徒数"),
                ),
                (
                    "billed_students",
                    models.IntegerField(default=0, verbose_name="課金対象生徒数"),
                ),
                ("price_per_student", models.IntegerField(verbose_name="単価（円）")),
                (
                    "total_amount",
                    models.IntegerField(default=0, verbose_name="合計金額（円）"),
                ),
                (
                    "classroom_details",
                    models.JSONField(default=dict, verbose_name="教室別詳細"),
                ),
                (
                    "student_details",
                    models.JSONField(default=dict, verbose_name="生徒詳細"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                        verbose_name="塾",
                    ),
                ),
            ],
            options={
                "verbose_name": "塾別課金レポート",
                "verbose_name_plural": "塾別課金レポート",
                "db_table": "school_billing_reports",
                "indexes": [
                    models.Index(
                        fields=["year", "period"], name="school_bill_year_866cd7_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="school_bill_generat_ecbd32_idx"
                    ),
                    models.Index(
                        fields=["school"], name="school_bill_school__003acb_idx"
                    ),
                ],
                "unique_together": {("school", "year", "period")},
            },
        ),
    ]
