# Generated by Django 4.2.7 on 2025-09-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0007_schoolbillingreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingReport',
        ),
    ]
