# Generated by Django 4.2.7 on 2025-09-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_schoolbillingreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbillingreport',
            options={'verbose_name': '課金レポート', 'verbose_name_plural': '課金レポート'},
        ),
    ]
