# Generated by Django 4.2.7 on 2025-10-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_alter_schoolbillingreport_options_and_more'),
        ('classrooms', '0008_auto_20250917_1256'),
    ]

    operations = [
    ]
