# Generated by Django 4.2.7 on 2025-11-24 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_can_input_scores_school_can_register_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', '6桁の数字で入力してください')], verbose_name='教室ID')),
                ('name', models.CharField(max_length=100, verbose_name='教室名')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school', verbose_name='塾')),
            ],
            options={
                'verbose_name': '教室',
                'verbose_name_plural': '教室',
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(choices=[('culture_kids', 'カルチャーキッズ導入塾'), ('general', '一般塾'), ('eduplus', 'eduplus導入塾')], max_length=20, unique=True, verbose_name='塾区分コード')),
                ('name', models.CharField(max_length=100, verbose_name='塾区分名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('price_per_student', models.IntegerField(verbose_name='1名あたり料金（円）')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '会員種別',
                'verbose_name_plural': '会員種別',
                'db_table': 'membership_types',
                'indexes': [models.Index(fields=['type_code'], name='membership__type_co_acf556_idx'), models.Index(fields=['is_active'], name='membership__is_acti_03fa19_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', '1〜10桁の数字で入力してください')], verbose_name='生徒ID')),
                ('name', models.CharField(max_length=100, verbose_name='生徒名')),
                ('grade', models.CharField(max_length=20, verbose_name='学年')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.classroom', verbose_name='教室')),
            ],
            options={
                'verbose_name': '生徒',
                'verbose_name_plural': '生徒',
                'db_table': 'students',
                'indexes': [models.Index(fields=['classroom', 'student_id'], name='students_classro_92fa8d_idx'), models.Index(fields=['student_id'], name='students_student_1ff8ed_idx'), models.Index(fields=['is_active'], name='students_is_acti_4aecc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolBillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('period', models.CharField(choices=[('spring', '春期'), ('summer', '夏期'), ('winter', '冬期')], max_length=10, verbose_name='期')),
                ('total_classrooms', models.IntegerField(default=0, verbose_name='教室数')),
                ('total_students', models.IntegerField(default=0, verbose_name='総生徒数')),
                ('billed_students', models.IntegerField(default=0, verbose_name='課金対象生徒数')),
                ('price_per_student', models.IntegerField(verbose_name='単価（円）')),
                ('total_amount', models.IntegerField(default=0, verbose_name='合計金額（円）')),
                ('classroom_details', models.JSONField(default=dict, verbose_name='教室別詳細')),
                ('student_details', models.JSONField(default=dict, verbose_name='生徒詳細')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='塾')),
            ],
            options={
                'verbose_name': '塾別課金レポート',
                'verbose_name_plural': '塾別課金レポート',
                'db_table': 'school_billing_reports',
                'indexes': [models.Index(fields=['year', 'period'], name='school_bill_year_866cd7_idx'), models.Index(fields=['generated_at'], name='school_bill_generat_ecbd32_idx'), models.Index(fields=['school'], name='school_bill_school__003acb_idx')],
                'unique_together': {('school', 'year', 'period')},
            },
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school', 'classroom_id'], name='classrooms_school__f6a8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='classrooms_is_acti_148ca3_idx'),
        ),
    ]
