# Generated by Django 4.2.7 on 2025-07-13 03:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "classrooms",
            "0002_alter_classroom_options_alter_classroom_classroom_id_and_more",
        ),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "生徒", "verbose_name_plural": "生徒"},
        ),
        migrations.AlterField(
            model_name="student",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="classrooms.classroom",
                verbose_name="教室",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="メールアドレス"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(max_length=20, verbose_name="学年"),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="生徒名"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "6桁の数字で入力してください"
                    )
                ],
                verbose_name="生徒ID",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
