# Generated by Django 4.2.7 on 2025-07-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "classrooms",
            "0002_alter_classroom_options_alter_classroom_classroom_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("eduplus", "eduplus会員"),
                    ("culture_kids", "カルチャーキッズ会員"),
                    ("non_member", "非会員"),
                ],
                default="non_member",
                max_length=20,
                verbose_name="会員種別",
            ),
        ),
        migrations.CreateModel(
            name="ClassroomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_register_students",
                    models.BooleanField(default=True, verbose_name="生徒登録権限"),
                ),
                (
                    "can_input_scores",
                    models.BooleanField(default=True, verbose_name="点数入力権限"),
                ),
                (
                    "can_download_tests",
                    models.BooleanField(
                        default=True, verbose_name="テスト問題ダウンロード権限"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "classroom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="classrooms.classroom",
                        verbose_name="教室",
                    ),
                ),
            ],
            options={
                "verbose_name": "教室権限設定",
                "verbose_name_plural": "教室権限設定",
                "db_table": "classroom_permissions",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10, verbose_name="生徒ID")),
                (
                    "student_name",
                    models.CharField(max_length=100, verbose_name="生徒名"),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("spring", "春期"),
                            ("summer", "夏期"),
                            ("winter", "冬期"),
                        ],
                        max_length=10,
                        verbose_name="期",
                    ),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="教科")),
                (
                    "has_score_input",
                    models.BooleanField(default=False, verbose_name="点数入力済み"),
                ),
                (
                    "score_input_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="点数入力日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classrooms.classroom",
                        verbose_name="教室",
                    ),
                ),
            ],
            options={
                "verbose_name": "受講記録",
                "verbose_name_plural": "受講記録",
                "db_table": "attendance_records",
                "indexes": [
                    models.Index(
                        fields=["classroom", "year", "period"],
                        name="attendance__classro_51c3b6_idx",
                    ),
                    models.Index(
                        fields=["has_score_input"],
                        name="attendance__has_sco_af21e1_idx",
                    ),
                    models.Index(
                        fields=["score_input_date"],
                        name="attendance__score_i_c83808_idx",
                    ),
                ],
                "unique_together": {
                    ("classroom", "student_id", "year", "period", "subject")
                },
            },
        ),
    ]
