# Generated by Django 4.2.7 on 2025-07-15 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestScheduleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}$", "4桁の年を入力してください"
                            )
                        ],
                        verbose_name="年度",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("summer", "夏期"), ("winter", "冬期")],
                        max_length=10,
                        verbose_name="期間",
                    ),
                ),
                ("planned_date", models.DateField(verbose_name="予定日")),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="実施日"),
                ),
                ("deadline", models.DateTimeField(verbose_name="締切日時")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("in_progress", "実施中"),
                            ("completed", "完了"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "テスト日程情報",
                "verbose_name_plural": "テスト日程情報",
                "db_table": "test_schedule_info",
                "indexes": [
                    models.Index(
                        fields=["year", "period"], name="test_schedu_year_10d688_idx"
                    ),
                    models.Index(
                        fields=["status"], name="test_schedu_status_9a3d32_idx"
                    ),
                ],
                "unique_together": {("year", "period")},
            },
        ),
    ]
