# Generated by Django 5.0 on 2025-07-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("japanese", "国語"),
                            ("math", "数学"),
                            ("english", "英語"),
                            ("science", "理科"),
                            ("social", "社会"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score_range_min", models.IntegerField()),
                ("score_range_max", models.IntegerField()),
                ("template_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_templates",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "comment_templates",
                "indexes": [
                    models.Index(
                        fields=["school", "subject"],
                        name="comment_tem_school__f55f22_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("answer", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="tests.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="students.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="tests.testdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "scores",
                "indexes": [
                    models.Index(
                        fields=["student", "test"], name="scores_student_81b46f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="scores_created_f9d909_idx"
                    ),
                ],
                "unique_together": {("student", "test", "question")},
            },
        ),
    ]
