# Generated by Django 4.2.7 on 2025-11-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_classroom_membershiptype_student_schoolbillingreport_and_more'),
        ('scores', '0013_alter_individualproblemscore_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttemplatev2',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_templates_v2', to='schools.classroom', verbose_name='教室（NULLの場合は塾全体）'),
        ),
        migrations.AddField(
            model_name='commenttemplatev2',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_templates_v2', to='schools.school', verbose_name='塾（NULLの場合はシステム共有）'),
        ),
        migrations.AlterField(
            model_name='individualproblemscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_problem_scores', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='questionscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='studentcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='subjectgeneralcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_general_comments', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='testattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attendances', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='testcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_comments', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='schools.student'),
        ),
        migrations.AddIndex(
            model_name='commenttemplatev2',
            index=models.Index(fields=['school', 'classroom'], name='comment_tem_school__427208_idx'),
        ),
        migrations.AddIndex(
            model_name='commenttemplatev2',
            index=models.Index(fields=['school', 'category'], name='comment_tem_school__0846a0_idx'),
        ),
    ]
