# Generated by Django 4.2.7 on 2025-07-13 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "塾", "verbose_name_plural": "塾"},
        ),
        migrations.AlterField(
            model_name="school",
            name="address",
            field=models.TextField(blank=True, verbose_name="住所"),
        ),
        migrations.AlterField(
            model_name="school",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="school",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="メールアドレス"),
        ),
        migrations.AlterField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ"),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=100, verbose_name="塾名"),
        ),
        migrations.AlterField(
            model_name="school",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_id",
            field=models.CharField(
                max_length=6,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "6桁の数字で入力してください"
                    )
                ],
                verbose_name="塾ID",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
