# Generated by Django 4.2.7 on 2025-07-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_testdefinition_subject"),
        ("schools", "0002_alter_school_options_alter_school_address_and_more"),
        ("students", "0002_alter_student_options_alter_student_classroom_and_more"),
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                ("total_classrooms", models.IntegerField(default=0)),
                ("active_classrooms", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "塾統計",
                "verbose_name_plural": "塾統計",
                "db_table": "school_statistics",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField()),
                ("correct_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("school_rank", models.IntegerField(blank=True, null=True)),
                ("national_rank", models.IntegerField(blank=True, null=True)),
                ("school_total_students", models.IntegerField(default=0)),
                ("national_total_students", models.IntegerField(default=0)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "test_results",
            },
        ),
        migrations.AddField(
            model_name="commenttemplate",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commenttemplate",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_templates",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="commenttemplate",
            name="subject",
            field=models.CharField(
                choices=[("japanese", "国語"), ("math", "算数")], max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="commenttemplate",
            index=models.Index(
                fields=["is_default", "subject"], name="comment_tem_is_defa_e7dddc_idx"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="tests.testdefinition",
            ),
        ),
        migrations.AddField(
            model_name="schoolstatistics",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["test", "total_score"], name="test_result_test_id_6738f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["student"], name="test_result_student_f8c645_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together={("student", "test")},
        ),
    ]
