# Generated by Django 4.2.7 on 2025-07-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0002_schoolstatistics_testresult_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commenttemplate",
            options={
                "verbose_name": "コメントテンプレート",
                "verbose_name_plural": "コメントテンプレート",
            },
        ),
        migrations.AlterModelOptions(
            name="score",
            options={"verbose_name": "得点", "verbose_name_plural": "得点"},
        ),
        migrations.AlterModelOptions(
            name="testresult",
            options={"verbose_name": "テスト結果", "verbose_name_plural": "テスト結果"},
        ),
    ]
