# Generated by Django 4.2.7 on 2025-07-13 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_testdefinition_answer_pdf_and_more"),
        ("students", "0002_alter_student_options_alter_student_classroom_and_more"),
        ("scores", "0003_alter_commenttemplate_options_alter_score_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="score",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="score",
            name="question_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="tests.questiongroup",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="comment",
            field=models.TextField(blank=True, verbose_name="コメント"),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(verbose_name="得点"),
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("student", "test", "question_group")},
        ),
        migrations.RemoveField(
            model_name="score",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="score",
            name="question",
        ),
    ]
