# Generated by Django 4.2.7 on 2025-07-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0009_remove_testdefinition_name"),
        ("schools", "0003_school_active_date_school_contact_person_and_more"),
        ("scores", "0004_alter_score_unique_together_score_question_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                ("period", models.CharField(max_length=10, verbose_name="時期")),
                ("subject", models.CharField(max_length=20, verbose_name="科目")),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="総受験者数"),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="平均点"
                    ),
                ),
                (
                    "average_correct_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="平均正答率",
                    ),
                ),
                ("max_score", models.IntegerField(default=100, verbose_name="満点")),
                (
                    "grade_statistics",
                    models.JSONField(default=dict, verbose_name="学年別統計"),
                ),
                (
                    "school_statistics",
                    models.JSONField(default=dict, verbose_name="塾別統計"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="集計日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="tests.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "テスト集計結果",
                "verbose_name_plural": "テスト集計結果",
                "db_table": "test_summaries",
            },
        ),
        migrations.CreateModel(
            name="SchoolTestSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_count",
                    models.IntegerField(default=0, verbose_name="受験者数"),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="平均点"
                    ),
                ),
                (
                    "average_correct_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="平均正答率",
                    ),
                ),
                (
                    "rank_among_schools",
                    models.IntegerField(blank=True, null=True, verbose_name="塾間順位"),
                ),
                (
                    "grade_details",
                    models.JSONField(default=dict, verbose_name="学年別詳細"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_summaries",
                        to="schools.school",
                    ),
                ),
                (
                    "test_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_details",
                        to="scores.testsummary",
                    ),
                ),
            ],
            options={
                "verbose_name": "塾別テスト集計",
                "verbose_name_plural": "塾別テスト集計",
                "db_table": "school_test_summaries",
            },
        ),
        migrations.AddIndex(
            model_name="testsummary",
            index=models.Index(
                fields=["year", "period", "subject"], name="test_summar_year_166226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testsummary",
            index=models.Index(
                fields=["calculated_at"], name="test_summar_calcula_74f85e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testsummary",
            unique_together={("test",)},
        ),
        migrations.AlterUniqueTogether(
            name="schooltestsummary",
            unique_together={("test_summary", "school")},
        ),
    ]
