# Generated by Django 4.2.7 on 2025-07-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0005_testsummary_schooltestsummary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="attendance",
            field=models.BooleanField(default=True, verbose_name="出席"),
        ),
    ]
