# Generated by Django 4.2.7 on 2025-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0006_score_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="is_rank_finalized",
            field=models.BooleanField(default=False, verbose_name="順位確定済み"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="national_rank_final",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="全国順位（確定）"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="national_rank_temporary",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="全国順位（一時）"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="national_total_final",
            field=models.IntegerField(default=0, verbose_name="全国受験者数（確定）"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="national_total_temporary",
            field=models.IntegerField(default=0, verbose_name="全国受験者数（一時）"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="rank_finalized_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="順位確定日時"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="school_rank_final",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="塾内順位（確定）"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="school_rank_temporary",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="塾内順位（一時）"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="school_total_final",
            field=models.IntegerField(default=0, verbose_name="塾内受験者数（確定）"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="school_total_temporary",
            field=models.IntegerField(default=0, verbose_name="塾内受験者数（一時）"),
        ),
    ]
