# Generated by Django 4.2.7 on 2025-07-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0010_alter_testdefinition_grade_level"),
        ("students", "0006_remove_phone_number"),
        ("scores", "0007_testresult_is_rank_finalized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_status",
                    models.IntegerField(
                        choices=[
                            (1, "出席"),
                            (0, "欠席"),
                            (2, "遅刻"),
                            (3, "早退"),
                            (4, "途中退席"),
                        ],
                        default=1,
                        verbose_name="出席状態",
                    ),
                ),
                (
                    "attendance_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="出席時刻"
                    ),
                ),
                (
                    "leave_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退席時刻"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="理由")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_questions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="遅刻・早退時に受験可能な問題を指定",
                        to="tests.question",
                        verbose_name="受験可能問題",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attendances",
                        to="students.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="tests.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "テスト出席管理",
                "verbose_name_plural": "テスト出席管理",
                "db_table": "test_attendances",
                "indexes": [
                    models.Index(
                        fields=["test", "attendance_status"],
                        name="test_attend_test_id_934637_idx",
                    ),
                    models.Index(
                        fields=["attendance_time"],
                        name="test_attend_attenda_5ad048_idx",
                    ),
                ],
                "unique_together": {("student", "test")},
            },
        ),
        migrations.CreateModel(
            name="QuestionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="得点")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="正答フラグ"),
                ),
                ("answer_text", models.TextField(blank=True, verbose_name="答案内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="tests.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_scores",
                        to="students.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_scores",
                        to="tests.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "小問得点",
                "verbose_name_plural": "小問得点",
                "db_table": "question_scores",
                "indexes": [
                    models.Index(
                        fields=["student", "test"],
                        name="question_sc_student_b1592a_idx",
                    ),
                    models.Index(
                        fields=["question"], name="question_sc_questio_70b35b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="question_sc_created_98875d_idx"
                    ),
                ],
                "unique_together": {("student", "test", "question")},
            },
        ),
    ]
