# Generated by Django 4.2.7 on 2025-07-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_remove_phone_number"),
        ("tests", "0010_alter_testdefinition_grade_level"),
        ("scores", "0009_commenttemplatev2_testcomment_studentcomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_number", models.IntegerField(verbose_name="問題番号")),
                ("max_score", models.IntegerField(default=10, verbose_name="満点")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="説明"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_problems",
                        to="tests.testdefinition",
                        verbose_name="テスト",
                    ),
                ),
            ],
            options={
                "verbose_name": "個別問題",
                "verbose_name_plural": "個別問題",
                "db_table": "individual_problems",
                "ordering": ["problem_number"],
            },
        ),
        migrations.CreateModel(
            name="IndividualProblemScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="得点")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="scores.individualproblem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_problem_scores",
                        to="students.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_problem_scores",
                        to="tests.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "個別問題得点",
                "verbose_name_plural": "個別問題得点",
                "db_table": "individual_problem_scores",
                "indexes": [
                    models.Index(
                        fields=["student", "test"],
                        name="individual__student_04983a_idx",
                    ),
                    models.Index(
                        fields=["problem"], name="individual__problem_d7c134_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="individual__created_2df2e7_idx"
                    ),
                ],
                "unique_together": {("student", "test", "problem")},
            },
        ),
        migrations.AddIndex(
            model_name="individualproblem",
            index=models.Index(
                fields=["test", "problem_number"], name="individual__test_id_52a4f7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="individualproblem",
            unique_together={("test", "problem_number")},
        ),
    ]
