# Generated by Django 4.2.7 on 2025-08-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0010_individualproblem_individualproblemscore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="grade_deviation_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="学年内偏差値",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="grade_rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="学年内順位"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="grade_total",
            field=models.IntegerField(default=0, verbose_name="学年内受験者数"),
        ),
        migrations.AddField(
            model_name="testresult",
            name="school_category_rank",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="小中区分内順位"
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="school_category_total",
            field=models.IntegerField(default=0, verbose_name="小中区分内受験者数"),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="is_rank_finalized",
            field=models.BooleanField(default=True, verbose_name="順位確定済み"),
        ),
    ]
