# Generated by Django 4.2.7 on 2025-08-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0011_testresult_grade_deviation_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="national_total",
            field=models.IntegerField(default=0, verbose_name="全国受験者数"),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="national_rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="全国順位"),
        ),
    ]
