# Generated by Django 4.2.7 on 2025-10-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_school_can_input_scores_school_can_register_students_and_more"),
        ("tests", "0013_alter_testdefinition_answer_pdf_and_more"),
        ("scores", "0012_testresult_national_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualproblemscore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_problem_scores",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="questionscore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_scores",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentcomment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="testattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_attendances",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="testcomment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_comments",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="SubjectGeneralComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[("japanese", "国語"), ("math", "算数")],
                        max_length=20,
                        verbose_name="教科",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="得点")),
                (
                    "score_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-20", "0-20点"),
                            ("21-40", "21-40点"),
                            ("41-60", "41-60点"),
                            ("61-80", "61-80点"),
                            ("81-100", "81-100点"),
                        ],
                        max_length=10,
                        verbose_name="点数範囲",
                    ),
                ),
                ("comment_text", models.TextField(verbose_name="総評コメント")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_general_comments",
                        to="students.student",
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_comments",
                        to="scores.commenttemplatev2",
                        verbose_name="使用テンプレート",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_general_comments",
                        to="tests.testdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "教科別総評コメント",
                "verbose_name_plural": "教科別総評コメント",
                "db_table": "subject_general_comments",
                "indexes": [
                    models.Index(
                        fields=["student", "test"],
                        name="subject_gen_student_55c5fa_idx",
                    ),
                    models.Index(
                        fields=["subject"], name="subject_gen_subject_b76643_idx"
                    ),
                    models.Index(
                        fields=["score_range"], name="subject_gen_score_r_d05d8b_idx"
                    ),
                ],
                "unique_together": {("student", "test", "subject")},
            },
        ),
    ]
