# Generated by Django 4.2.7 on 2025-07-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0009_remove_testdefinition_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdefinition",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("elementary_1", "小学1年生"),
                    ("elementary_2", "小学2年生"),
                    ("elementary_3", "小学3年生"),
                    ("elementary_4", "小学4年生"),
                    ("elementary_5", "小学5年生"),
                    ("elementary_6", "小学6年生"),
                    ("middle_1", "中学1年生"),
                    ("middle_2", "中学2年生"),
                    ("middle_3", "中学3年生"),
                ],
                default="elementary_1",
                max_length=20,
                verbose_name="対象学年",
            ),
        ),
    ]
