# Generated by Django 4.2.7 on 2025-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testscheduleinfo",
            name="period",
            field=models.CharField(
                choices=[("spring", "春期"), ("summer", "夏期"), ("winter", "冬期")],
                max_length=10,
                verbose_name="期間",
            ),
        ),
    ]
